title: אקולוגיה
author: יגאל אראל
logo: logo.png

execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
repository:
  url: https://github.com/TomerVagenfeld/Ecology-Book
  branch: main

parse:
  myst_enable_extensions:
    - deflist
    - colon_fence
    - substitution
    - linkify
    - dollarmath
    - amsmath

sphinx:
  config:
    language: he
    numfig: false
    mathjax3_config:
      tex:
        displayMath: [["$$", "$$"], ["\\[", "\\]"]]
        inlineMath: [["$", "$"], ["\\(", "\\)"]]
    exclude_patterns:
      - "_build/**"
      - "pipeline/**"
      - ".ipynb_checkpoints/**"
      - "igal_original_docx/**"
      - "figs/**"
  html_static_path: ["_static"]
  html_css_files:
    - "style.css"
  html_js_files:
    - "rtl-sidebar.js"
    - "footnote-dir.js"
    - "list-dir.js"
    - "en-quote.js"
    - "footnote-tooltip.js"
    - "search-hebrew.js"
    - "search-scroll.js"
    - "image-zoom.js"

html:
  use_issues_button: false
  use_repository_button: false
  use_multitoc_numbering: false
  extra_footer: "יגאל אראל 2025"
