title: Ecology Book
author: Yigal Erel
logo: book-source/media/logo.png

execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    numfig: false
    exclude_patterns:
      - "_build/**"
      - "_build/*"
      - "book-source/docx/**"
      - "**/_build/**"
      - ".ipynb_checkpoints/**"
  html_static_path: ["_static"]
  html_css_files:
    - "style.css"
  html_js_files:
    - "rtl-sidebar.js"
    - "footnote-dir.js"
    - "list-dir.js"
    - "en-quote.js"


html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
  extra_context:
    default_mode: light
  search:
    search_snippets: true
    search_language: he
    search_prebuild_index: true
    search_snippet_length: 100
    extra_footer: "Yigal Erel 2025"
    announcement: "hi"
