#!/usr/bin/env python3
"""
Fix malformed English quote blocks in markdown files.

This script fixes issues where:
1. :::{div} .en-quote blocks are not properly closed
2. English quote blocks wrap H1 titles (preventing Sphinx from detecting them)
3. Multiple small blocks should be merged into one cohesive block

The script ensures that all English quote div blocks are closed BEFORE the first H1 title.
"""

import re
import sys
from pathlib import Path


def fix_en_quote_blocks(md_text: str) -> str:
    """
    Fix English quote blocks to ensure they're properly structured.

    Rules:
    - All :::{div} .en-quote or ::::{div} .en-quote blocks must be closed
    - No div block should wrap an H1 heading
    - English quotes before the first H1 should be in a single div block
    """
    # Pre-sanitize: fix double-brace issues like :::{{div}} -> :::{div}
    # This handles files generated by older code versions or manual edits
    md_text = re.sub(r'(:::+)\{\{div\}\}', r'\1{div}', md_text)

    lines = md_text.splitlines()
    out = []
    i = 0

    # Track if we're in an en-quote block
    in_en_quote = False
    en_quote_indent = ""
    en_quote_colons = 3  # number of colons used (3 or 4)
    en_quote_content = []

    while i < len(lines):
        line = lines[i]

        # Check for en-quote block start (including malformed :::{::}{div} syntax)
        en_quote_start = re.match(r'^([ \t]*)::.*\{div\}\s+\.en-quote\s*$', line)
        if en_quote_start and not in_en_quote:
            en_quote_indent = en_quote_start.group(1)
            in_en_quote = True
            en_quote_content = []
            i += 1
            continue

        # Check for closing fence (2, 3, or 4 colons)
        if in_en_quote:
            closing_fence = re.match(r'^([ \t]*)::+\s*$', line)
            if closing_fence and closing_fence.group(1) == en_quote_indent:
                # Closing fence found - output the en-quote block
                if en_quote_content:
                    out.append(f"{en_quote_indent}:::{{div}} .en-quote")
                    out.append("")
                    out.extend(en_quote_content)
                    out.append(f"{en_quote_indent}:::")
                in_en_quote = False
                en_quote_content = []
                i += 1
                continue

            # Check if we hit an H1 - if so, close the en-quote block first
            if re.match(r'^\s*#\s+', line):
                # Close the en-quote block
                if en_quote_content:
                    out.append(f"{en_quote_indent}:::{{div}} .en-quote")
                    out.append("")
                    out.extend(en_quote_content)
                    out.append(f"{en_quote_indent}:::")
                    out.append("")  # Add blank line before H1
                in_en_quote = False
                en_quote_content = []
                # Don't increment i, process this line again
                continue

            # Content inside en-quote block
            en_quote_content.append(line)
            i += 1
            continue

        # Not in en-quote block - just pass through
        out.append(line)
        i += 1

    # If we're still in an en-quote block at the end, close it
    if in_en_quote and en_quote_content:
        out.append("")
        out.append(f"{en_quote_indent}:::{{div}} .en-quote")
        out.append("")
        out.extend(en_quote_content)
        out.append(f"{en_quote_indent}:::")

    result = "\n".join(out)
    if md_text.endswith("\n") and not result.endswith("\n"):
        result += "\n"
    return result


def fix_en_quote_blocks_file(md_path: Path) -> bool:
    """Fix en-quote blocks in a file. Returns True if changes were made."""
    text = md_path.read_text(encoding="utf-8")
    fixed = fix_en_quote_blocks(text)

    if fixed != text:
        md_path.write_text(fixed, encoding="utf-8")
        return True
    return False


def main():
    if len(sys.argv) > 1:
        # Fix specific files
        files = [Path(p) for p in sys.argv[1:]]
    else:
        # Fix all chapter markdown files
        files = list(Path("book-source/md").glob("ch*.md"))

    print(f"Fixing {len(files)} files...")
    for md_path in files:
        if fix_en_quote_blocks_file(md_path):
            print(f"[FIXED] {md_path}")
        else:
            print(f"[OK] {md_path}")

    print("\nDone!")


if __name__ == "__main__":
    main()
